### ISSUE TITLE
lge-hammerhead: Cannot boot pmOS or TWRP on D820/D821(H)

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [msm8916-mainline/lk2nd#105]
There are at least 4 hammehead models: D820/D821(E) and D820/D821(H).
E stands for ``elpida`` and H stands for ``hynix``.
pmOS and TWRP are able to boot on ``androidboot.hardware.ddr=elpida`` devices with the device tree but not on ``androidboot.hardware.ddr=hynix`` devices.
[lk_log-d820(h).txt](https://github.com/msm8916-mainline/lk2nd/files/7293509/lk_log-d820.h.txt)
[lk_log-d821(h).txt](https://github.com/msm8916-mainline/lk2nd/files/7293510/lk_log-d821.h.txt)

**Comment by Minecrell** [comment]
I don't really understand this, perhaps an UART log or at least a detailed description of what happens when booting pmOS or TWRP would be helpful.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
It's possible to check this in stock bootloader.
![elpida](https://fscl01.fonpit.de/userfiles/4774964/image/AndroidPIT-Nexus-5-Fastboot-unlocked-w628.JPG)

Or you can get ``androidboot.hardware.ddr=elpida`` by running this in lk2nd:
```
fastboot oem lk_log && fastboot get_staged /dev/stdout # To stdout
fastboot oem lk_log && fastboot get_staged lk_log.txt # To file lk_log.txt
```

**Comment by minlexx** [comment]
I can't confirm. I just built lk2nd from current master and it just works fine.

I have model D821(H) 32 Gb:

![изображение](https://user-images.githubusercontent.com/13084776/137331706-97827e2b-76e7-4486-862b-6a850b63293d.png)

and current lk2nd works.

![lk2nd-hh-screenshot](https://user-images.githubusercontent.com/13084776/137332221-ac8f0300-c2a6-4cd6-a251-42328ef5b624.png)

lk_log: [lk_log_hh.txt](https://github.com/msm8916-mainline/lk2nd/files/7346545/lk_log_hh.txt)

**Comment by Justinzobel** [comment]
> I can't confirm. I just built lk2nd from current master and it just works fine.
> 
> I have model D821(H) 32 Gb:
> 
> ![изображение](https://user-images.githubusercontent.com/13084776/137331706-97827e2b-76e7-4486-862b-6a850b63293d.png)
> 
> and current lk2nd works.
> 
> ![lk2nd-hh-screenshot](https://user-images.githubusercontent.com/13084776/137332221-ac8f0300-c2a6-4cd6-a251-42328ef5b624.png)
> 
> lk_log: [lk_log_hh.txt](https://github.com/msm8916-mainline/lk2nd/files/7346545/lk_log_hh.txt)
> 
> I haven't tried to boot TWRP yet, but it boots pmOS just fine.

So if I have the H I should be able to install the lk2nd for a better experience?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
@Justinzobel lk2nd is a solution to [pmaports#1227](https://gitlab.com/postmarketOS/pmaports/-/issues/1227), to make sure hammerhead boot correctly and avoid confusion. But it's currently solved with another solution.

**Comment by Icenowy** [comment]
0.11.0 works my on D820(H).

**Comment by stephan-gh** [comment]
@wonderfulShrineMaidenOfParadise Given the successful test reports, can we close this issue?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
lk2nd for hammerhead seems to be ready. Close.
