### ISSUE TITLE
[SM-P550] Not booting to stock android.

### ISSUE THREAD

**Issue by danfragoso** [msm8916-mainline/lk2nd#120]
Hi, I'm using the Samsung Galaxy Tab A 9.7 2015 [SM-P550] and after flashing the lk2nd bootloader I can't boot into stock android anymore, when selecting the `START` entry it just reboots to lk2nd. But it works with postmarketos, either when I flash it or load from the sdcard. The stock firmware version is `P550XXU1CSJ2_P550ZTO1CSJ2`.

Here is the [log](https://gist.github.com/danfragoso/e4d421b528cba298f50378c710a69848) file captured with `fastboot oem lk_log && fastboot get_staged`

**Comment by TravMurav** [comment]
Hi, lk2nd replaces android kernel boot.img so to boot into android you have to install it back via lk2nd (It will flash it with the offset and boot when it can't find any ext2 boot partition like the one postmarketOS provides)

However I think we don't have P variant in the lk2nd dtb configs: In this case the device should be added to lk2nd first so it can recognize it and know how to boot the downstream boot images:

A change similar to this would be needed: 
https://github.com/msm8916-mainline/lk2nd/commit/dcbdfee08379b017541d8f466e638a27e6de8628#

To know, which file you need to add it to, you should see a line "DTB - <...>" on the lk2nd screen. It shows msm-id and board-id that are present in each dts file.
Usually for Samsung the last number is "revision", we mark those as -rXX

After you add the device node, your lk2nd screen should start showing the model you have selected and *usually* this is enough for android images to boot.
