### ISSUE TITLE
[SM-G530H] does not appear on fastboot devices

### ISSUE THREAD

**Issue by alfr3dosv** [msm8916-mainline/lk2nd#152]
I flashed lk2nd-msm8916 using heimdall, I can boot into lk2nd, it shows that it is in fastboot mode, but so far I haven't been able to detect it on windows or linux using `fastboot devices`

I guess it's because the only ones supported in this family are Samsung Galaxy Grand Prime - SM-G530W, SM-G530Y

**Comment by TravMurav** [comment]
Hi, for this device lk2nd has to enable usb properly which it only can do if it can detect the device. You have to add something like this:

https://github.com/msm8916-mainline/lk2nd/blob/master/dts/msm8916/msm8916-samsung-r02.dts#L25-L34

for your variant, then lk2nd should work correctly. I believe it should already show the "DTB" line that would hint which dts file to edit.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
PR #151 is on the way.

**Comment by alfr3dosv** [comment]
Hi thanks for your work, looking forward to test it
