### ISSUE TITLE
Please support SM-T560

### ISSUE THREAD

**Issue by montvid** [msm8916-mainline/lk2nd#171]
SM-T560NU is supported but SM-T560 is not. The file for SM-T560NU does not work on SM-T560. Thank you for your consideration. I could test the new builds.

**Comment by stephan-gh** [comment]
While they are named similarly and probably look similar, it seems like the hardware inside is totally different for SM-T560**NU** and SM-T560. Unlike the **NU** version, the SM-T560 seems to be based on a Spreadtrum (not Qualcomm) processor that cannot be supported by this project. Sorry :(
