### ISSUE TITLE
Allow additional DT change(s) from panel selector

### ISSUE THREAD

**Issue by vknecht** [msm8916-mainline/lk2nd#174]
There are idol3 variants with different panels and touchscreen.
It seems those are paired (eg. nt35596 panel + rmi4, and r63315 panel + edt5x06).
Ideally, lk2nd would enable the expected touchscreen and disable the other one.

How should such feature be implemented ?
Some guidelines would be nice, and I can get a go at it.

**Comment by z3ntu** [comment]
Fixed by #217 ?

**Comment by vknecht** [comment]
Indeed :-)
Next step would be i2c probing I guess...
