### ISSUE TITLE
Load new OS or Kernel doesnt work

### ISSUE THREAD

**Issue by red0bear** [msm8916-mainline/lk2nd#192]
Well, i already tried many ways to load kernel or OS build from pmbootstrap, but all them fail to load stuff on Cellphone proper enabled on Dev config.

i have try used adb who see devices connected but heimdall/fastboot/pmbootstrap aways wait to some devices appear; heimdall try install but fails as show below:  

Initialising protocol...
Protocol initialisation successful.

Beginning session...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...

Some devices may take up to 2 minutes to respond.
Please be patient!

WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
Session begun.

WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
Downloading device's PIT file...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
PIT file download successful.

Uploading RECOVERY
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
0%WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...

1%

2%
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
ERROR: Failed to unpack received packet.

ERROR: Failed to confirm end of file transfer sequence!
ERROR: RECOVERY upload failed!

Ending session...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
Rebooting device...
WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
Releasing device interface.

should be easy see on steps you and others showed to install , but am facing this barrer. Any help could be welcomed.

**Comment by stephan-gh** [comment]
Try a different cable/USB port/PC maybe?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Umm, does it have something to do with lk2nd?

Also make sure it's a J5 2015 (`SM-J500*`) or J5 2016 (`SM-J510*`). If it's none of them, then it's not MSM8916, which is not supported.
> J5 from 2015 there is no fastboot

According to your description, it seems that you haven't flashed lk2nd yet.
You need to do `heimdall flash --BOOT lk2nd.img` before you flash postmarketOS with `fastboot` or `pmbootstrap flasher flash_rootfs --userdata`.
