### ISSUE TITLE
Post a new device

### ISSUE THREAD

**Issue by bzy-080408** [msm8916-mainline/lk2nd#195]
How can I post this projcet on a new device(based on msm8974)?
I need help,the device is ZTE S 291(or ZTE Grand SII);
Thanks.

**Comment by Newbytee** [comment]
I would suggest you join the postmarketOS Mainline channel where we can help you with this. More information about that here: https://wiki.postmarketos.org/wiki/Matrix_and_IRC

**Comment by stephan-gh** [comment]
Please join the chat at [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org) (or `#msm8916-mainline` on irc.oftc.net) for device support and porting help. Hard to help here in GitHub issues.
