### ISSUE TITLE
Can't flash motorola harpia

### ISSUE THREAD

**Issue by MichalkapDeveloper** [msm8916-mainline/lk2nd#200]
I cant flash to Moto G4 Play harpia.
Terminal output:
"(bootloader) has-slot:boot: not found
(bootloader) is-logical:boot: not found
Sending 'boot' (494 KB)                            OKAY [  0.042s]
Writing 'boot'                                     (bootloader) Image not signed or corrupt

OKAY [  0.052s]
Finished. Total time: 0.153s"

**Comment by MichalkapDeveloper** [comment]
: boot : always turns into :boot:

**Comment by stephan-gh** [comment]
Try `fastboot boot lk2nd.img` first then do `fastboot flash lk2nd lk2nd.img`.

**Comment by MichalkapDeveloper** [comment]
Does not work

**Comment by stephan-gh** [comment]
Why?

**Comment by ph1-xyz** [comment]
Similar problem here, but with motorola-osprey

**Comment by ph1-xyz** [comment]
> Why do you select recovery if you want to boot into lk2nd?

I may be doing the wrong thing, but either rebooting seemed to bring me again to the Fastboot menu :-/

**Comment by stephan-gh** [comment]
Please join the chat at [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org) (or `#msm8916-mainline` on irc.oftc.net) for device support. Hard to help here in GitHub issues.
