### ISSUE TITLE
Touchscreen don't work and Boot can't showing as only black screen on ASUS_Z00T

### ISSUE THREAD

**Issue by johnelmermin227** [msm8916-mainline/lk2nd#201]
Hi i have encountered problem when i trying to install PostmarketOS gnome on Asus Zenfone 2 Laser 1080P variant. Until after asus logo can't showing a postmarketos logo it only shown Black screen but it's booted in 2 minutes only. And after booted Touchscreen not working it's only mousepad can used on touch it looks hard to touch and it's controlled by mouse. Any help?

It's according postmarketos wiki said Touch screen works but nothing works on me

**Comment by stephan-gh** [comment]
Asus Zenfone 2 Laser 1080P (aka z00t and not z00l) is not supported in the msm8916-mainline Linux yet and we can't provide support for the downstream port in postmarketOS here, sorry.
