### ISSUE TITLE
Galaxy A3 with product name SM-A3009 is not supported.

### ISSUE THREAD

**Issue by water-chika** [msm8916-mainline/lk2nd#209]
When I see that a Samsung Galaxy A3 phone could run postmarketOS, I buy one. But when I try to run lk2nd, I find that my Galaxy A3 is SM-A3008 and that one is not supported by lk2nd. I have tryed some methods such as modifying dts... But I do not known which downstream is about SM-A3009. Is there are some quick method to add support for SM-A3009. Or some help that could let me known how to add support for a variant of Samsung Galaxy A3.
Thanks for reading.

**Comment by stephan-gh** [comment]
What happens if you flash lk2nd? Does it boot?

**Comment by water-chika** [comment]
> What happens if you flash lk2nd? Does it boot?

It shows red text "Could not do normal boot." in Samsung Download mode

**Comment by stephan-gh** [comment]
Are you sure the device actually allows flashing custom software? A3009 seems to be a carrier device (China Telecom) and I'm not sure what the rules for those are. Is there something like TWRP for this device that you could try?

**Comment by water-chika** [comment]
First 

> > What happens if you flash lk2nd? Does it boot?
> 
> It shows red text "Could not do normal boot." in Samsung Download mode

It will flash success, and reboot. But after reboot it will re-enter Samsung Download mode and show that text in above other text.

**Comment by water-chika** [comment]
Yes, I tried TWRP. And that could run recovery mode.

**Comment by stephan-gh** [comment]
Can you post a link to the TWRP image that works correctly?

**Comment by water-chika** [comment]
https://dl.twrp.me/a3xelte

**Comment by stephan-gh** [comment]
a3xelte is for the A3 (2016) though and not the A3 (2015). Are you sure you actually have a A3009 with Qualcomm Snapdragon 410/MSM8916?

**Comment by water-chika** [comment]
I plan to install LineageOS, but there is not a rom in official website. And build a rom need a lot of time and a lot of disk space.

**Comment by water-chika** [comment]
Yes, it shows "product name: SM-A3009"

**Comment by stephan-gh** [comment]
https://dl.twrp.me/a3xelte shouldn't work on SM-A3009 though...

**Comment by water-chika** [comment]
After I flash it into RECOVERY partition, it could go into recovery mode by pressing Volumn Up + Home + Power.

**Comment by water-chika** [comment]
Let me try flashing some other data into this partion. And I can not go into recovery mode now.
Try flashing twrp, it shows "Failed to confirm end of file transfer sequence!" in my terminal that run "heimdall flash --RECOVERY twrp.img".
Maybe there are some problems in this phone. I will try some other method and I will tell you if  this phone could run properly.
Thanks for your help!

**Comment by water-chika** [comment]
I tryied run "heimdall flash --RECOVERY twrp.img --no-reboot", and it show "binary size is too large : recovery".
It is my problem that I do not flash it into RECOVERY.

**Comment by stephan-gh** [comment]
Can you try this one? (please unpack it first) [lk2nd-a3.zip](https://github.com/msm8916-mainline/lk2nd/files/9963614/lk2nd-a3.zip)

**Comment by water-chika** [comment]
It shows yellow texts "Set Warranty Bit : kernel"

**Comment by stephan-gh** [comment]
And then? Nothing happens?

**Comment by water-chika** [comment]
Nothing happened. Just show samsung logo or show charging picture. The yellow texts show above logo or picture.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Please join the matrix chat, [#mainline:postmarketos.org](https://matrix.to/#/#mainline:postmarketos.org) for porting.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
We have new matrix room now. Please join [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org) if you still need help with porting.
