### ISSUE TITLE
Actual support for SM-T350?

### ISSUE THREAD

**Issue by operamilkmandolinneo12** [msm8916-mainline/lk2nd#224]
Hello. I looked up installing pmOS for SM-T350 but according to this repo that it doesn't list the device.

However I still tried it. I used `heimdall` to install the bootloader but after installation, somehow `fastboot devices` doesn't recognize the device. 

I went back to the latest Nougat stock image. I would like to hear feedback for the support, thank you.

**Comment by stephan-gh** [comment]
You probably just need to add a device tree entry for the device. Please join the chat for device porting help.

**Comment by operamilkmandolinneo12** [comment]
> You probably just need to add a device tree entry for the device. Please join the chat for device porting help.

Alright, thank you!
