### ISSUE TITLE
quesiton on MSM8994

### ISSUE THREAD

**Issue by decaduto** [msm8916-mainline/lk2nd#227]
Hello, a fast question: is the source for msm8994 also valid for msm8992? here i see some code in common https://source.codeaurora.org/quic/la/kernel/lk/log/platform/msm8994?qt=grep&q=8992

**Comment by stephan-gh** [comment]
Yes. For 8994/8992 please use the new `experimental-tmp2` branch, it will become the main branch eventually (although currently it's still missing some features).

**Comment by decaduto** [comment]
Thank you, before I tried with the main branch and the sources for msm8994 seems broken, the experimental-tmp2 compiles without any problem, I close the issue right now.
Thank you again for your effort.
