### ISSUE TITLE
Samsung A5 (SM-A5000) support 

### ISSUE THREAD

**Issue by exkc** [msm8916-mainline/lk2nd#251]
![Screenshot_20230501-031015_Gallery](https://user-images.githubusercontent.com/70055899/235371900-4528cb7b-4dbc-4162-9459-c0b12d0100fc.png)

**Comment by exkc** [comment]
mainline linux boot via lk2nd and it support the panel that it use.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Consider joining [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org) if you feel like to do it.
