### ISSUE TITLE
Support for Alcatel P350x (One Touch 8S)

### ISSUE THREAD

**Issue by KhazAkar** [msm8916-mainline/lk2nd#254]
Hi!
I currently own such device, but with Orange branding (Orange Sego). Is there any chance to get lk2nd running here? It have msm8916 chipset.
If any more data is necessary, please let me know :)

**Comment by stephan-gh** [comment]
Sometimes such branded devices have locked down secure boot that will not allow booting custom software. Still, it's definitely worth further investigation.

You can check the [MSM8916 Mainlining](https://wiki.postmarketos.org/wiki/MSM8916_Mainlining) guide for some general hints about porting lk2nd and mainline Linux. If you need help, please join [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org). It's easier to help with porting in the chat.
