### ISSUE TITLE
feature request: support extlinux.conf

### ISSUE THREAD

**Issue by jenneron** [msm8916-mainline/lk2nd#275]
Make it using kernel, dtb and initramfs specified in extlinux/extlinux.conf on boot partition instead of boot.img.

extlinux supports 2 ways of specifying dtb: `fdt /something.dtb` and `fdtdir /dtbs`. The last one assumes bootloader (lk2nd in our case) to select correct dtb from the directory, and this would allow us to make generic ports or a generic installer for multiple SoCs like I want with chrome os devices

This way we would be consistent with syslinux and U-Boot.

See https://u-boot.readthedocs.io/en/latest/develop/distro.html?highlight=extlinux#boot-configuration-files, also see
https://gitlab.com/postmarketOS/boot-deploy/-/commit/58502ec3bf192452c1a862849892349293e138b7

**Comment by wonderfulShrineMaidenOfParadise** [comment]
We can use extlinux on branch `main` now.
