### ISSUE TITLE
Support for Samsung Galaxy Ace Style SM-G357FZ

### ISSUE THREAD

**Issue by arthurlutz** [msm8916-mainline/lk2nd#28]
According to the wikipedia page https://en.wikipedia.org/wiki/Samsung_Galaxy_Ace_4 the SM-G357FZ uses Snapdragon 410 MSM8916. 

Any chance of getting lk2nd working with it ? (and by extension postmarketos). I have one at hand and would be able to test it out / debug stuff.

**Comment by Minecrell** [comment]
If you have MSM8916 (Snapdragon 410) there is a good chance that you can get something working.

Please take a look at this wiki page: https://wiki.postmarketos.org/wiki/MSM8916_Mainlining
and join the [postmarketOS mainlining channel](https://wiki.postmarketos.org/wiki/Matrix_and_IRC) for help (available via IRC or Matrix).

**Comment by Minecrell** [comment]
Please let us know if you need any further help, I will close this for now :)
