### ISSUE TITLE
Please add support for Galaxy A5 (SM-A500G)

### ISSUE THREAD

**Issue by Hassan-kareem** [msm8916-mainline/lk2nd#298]
And please give your Telegram group or other support group

**Comment by wonderfulShrineMaidenOfParadise** [comment]
We don't have Telegram. Please join [#msm8916:postmarketos.org](https://app.element.io/#/room/#msm8916:postmarketos.org) for faster helps.

**Comment by Hassan-kareem** [comment]
Ok
Thanks
