### ISSUE TITLE
Support request 

### ISSUE THREAD

**Issue by shashankx86** [msm8916-mainline/lk2nd#310]
Hi,

Can you add support for MDM9207
Thank you

**Comment by stephan-gh** [comment]
The experimental-tmp3 branch should have support for MDM9207. If you need specific help, please join the chat (e.g. [#lk2nd:postmarketos.org on Matrix](https://matrix.to/#/#lk2nd:postmarketos.org)).

**Comment by shashankx86** [comment]
I am not asking for exact ETA, 
how much estimated time it may take come at main
and is it usable?

**Comment by stephan-gh** [comment]
It's quite usable already.

**Comment by shashankx86** [comment]
experimental-tmp3, right?

**Comment by shashankx86** [comment]
@stephan-gh checked
MDM9207 not there, i think you are confused with MDM9607

**Comment by shashankx86** [comment]
@stephan-gh 
one more thing 
as build guide says 
```
$ make TOOLCHAIN_PREFIX=arm-none-eabi- lk2nd-msmXXXX
```
but my device doesn't have any cpu, it just uses MDM9207
and in boot logs it show CPU as 
```
<6>[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c53c7d
```

full boot logs here
https://github.com/ExtendedFi/JMR540_proc_Dump/blob/main/kmsg

**Comment by stephan-gh** [comment]
`make TOOLCHAIN_PREFIX=arm-none-eabi- lk2nd-mdm9607`

**Comment by xxhg** [comment]
Can it support SM8250?

**Comment by xxhg** [comment]
> `make TOOLCHAIN_PREFIX=arm-none-eabi- lk2nd-mdm9607`

Can it support SM8250?
