### ISSUE TITLE
`Error code 3039 at boot_elf_loader.c Line 1413` On UART after flashing ABOOT partition

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [msm8916-mainline/lk2nd#331]
Hi there,

I flashed the prebuilt MSM8916 on to my Lenovo A6000's ABOOT partition using edl tools.
Now I get no display and on my UART I get `Error code 3039 at boot_elf_loader.c Line 1413`
I'm unable to force the device into edl mode and it gets detected as `QHSUSB__BULK` on my linux PC. I don't know how to proceed from here.

Please Help me.

![image](https://github.com/msm8916-mainline/lk2nd/assets/89782177/6b500c75-86f7-4443-ba5b-004a7ad72ce0)

And also multiple USB drives are appearing on my PC.

![image](https://github.com/msm8916-mainline/lk2nd/assets/89782177/bf9f99ba-06d9-4ff7-b457-0b0462791458)
(All of them expect `Data`)

**Comment by TravMurav** [comment]
Hi!

If you flashed lk2nd.img to `aboot`, you installed it incorrectly and destroyed your original android bootloader. lk2nd.img is supposed to be installed in `boot` instead.

I suggest you to restore `aboot` from the backup you made and install lk2nd correctly.

**Comment by ElectroBoy404NotFound** [comment]
> Hi!
> 
> If you flashed lk2nd.img to `aboot`, you installed it incorrectly and destroyed your original android bootloader. lk2nd.img is supposed to be installed in `boot` instead.
> 
> I suggest you to restore `aboot` from the backup you made and install lk2nd correctly.

Ah, but how do I do that? Now even the USB drives aren't showing up

**Comment by TravMurav** [comment]
Switch the device into EDL the same way you did before and flash aboot back.

**Comment by ElectroBoy404NotFound** [comment]
> Switch the device into EDL the same way you did before and flash aboot back.

I used the button combo, now the combo does nothing

**Comment by ElectroBoy404NotFound** [comment]
Also looks like I destroyed the ABOOT partition even more as now this is what I get:
![image](https://github.com/msm8916-mainline/lk2nd/assets/89782177/2d31f1fb-ad51-4ada-9196-4590b4b0b539)

**Comment by ElectroBoy404NotFound** [comment]
Ok, finally after a lot of google, I found the EMMC pins and shorted the CLK pin to force the mobile into edl. Thank you for your help!
