### ISSUE TITLE
 dts: msm8974: hammerhead: cannot boot lk2nd-msm8974.img 17.0

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [msm8916-mainline/lk2nd#370]
On hammerhead, it cannot boot lk2nd-msm8974.img 17.0 after `fastboot flash boot lk2nd-msm8974.img` in stock fastboot.

To workaround this, we need to drop `msm8974pro-ab-pm8941-mtp.dtb` and `msm8974pro-ac-pm8941-mtp.dtb` from `rules.mk`.

**Comment by barni2000** [comment]
Possible workaround LK2ND_DTBS="" LK2ND_ADTBS='msm8974-lge-hammerhead.dtb'

**Comment by barni2000** [comment]
> Possible workaround LK2ND_DTBS="" LK2ND_ADTBS='msm8974-lge-hammerhead.dtb'

another possible workaround is `LK2ND_QCDTBS=""`

**Comment by barni2000** [comment]
> On hammerhead, it cannot boot lk2nd-msm8974.img 17.0 after `fastboot flash boot lk2nd-msm8974.img` in stock fastboot.
> 
> To workaround this, we need to drop `msm8974pro-ab-pm8941-mtp.dtb` and `msm8974pro-ac-pm8941-mtp.dtb` from `rules.mk`.

This workaround is not working anymore.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
> This workaround is not working anymore.

It still works on 19.0, but I see your fix working as well. Closing.
