### ISSUE TITLE
[feature] a way to poweroff the screen while staying on lk2nd screen or charging

### ISSUE THREAD

**Issue by lm2lm2** [msm8916-mainline/lk2nd#402]
a way to poweroff the screen while staying on lk2nd screen or charging, eg for a certain time, or until next reboot by usb unplug/replug

**Comment by TravMurav** [comment]
Hi!

Display power and backlight is largely device-specific so it would require work to enable the display control for each specific device. Because of this, and since lk2nd is not /supposed/ to be "stayed in", this feature is out-of-scope.
