### ISSUE TITLE
lk2nd cannot work well with multi dtbs?

### ISSUE THREAD

**Issue by mxpro1996** [msm8916-mainline/lk2nd#57]
Model:SM-G5108Q
I add its model and qcom,msm-id/qcom,board-id to "msm8916-samsung-r08.dts" to build.After flashing "lk2nd.img" ,it stays at Odin Mode and says "cannot do normal boot".

But after deleting other dtbs of the
"lk2nd/dts/msm8916/rules.mk" ,lk2nd can normally work on SM-G5108Q.

**Comment by mxpro1996** [comment]
This is a modified fork of lk2nd

**Comment by mxpro1996** [comment]
This is a modified fork.
https://github.com/mxpro1996/lk2nd-Samsung-G5108Q

**Comment by Minecrell** [comment]
I'm not sure. Some devices have weird bootloaders. As a first step, as long as you have lk2nd booting _somehow_ it's fairly good already.
